version: '3.1'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
    ports:
      - 9200:9200
    environment:
      xpack.security.enabled: 'false'
      discovery.type: single-node
